### ISSUE TITLE
Mehrere Prüfungen mit gleichem Namen

### ISSUE THREAD

**Issue by mathebell** [mangei/tissquickregistrationscript#17]
Hi!

Ich hatte gerade die Anmeldung zu https://tiss.tuwien.ac.at/education/course/examDateList.xhtml?dswid=6008&dsrid=901&courseNr=104396&semester=2020S

Hier hießen leider alle Prüfungen gleich und ich hatte auch dateOfExam gesetzt (auf das erste Datum). Es hat aber das unterste ausgewählt. Wäre cool, wenn das noch behoben werden könnte.

**Comment by mangei** [comment]
dateOfExam wird nun auch unterstützt, dank des beitrags der community ❤️ 
https://github.com/mangei/tissquickregistrationscript/pull/18
