### ISSUE TITLE
Will you be developing this script further?

### ISSUE THREAD

**Issue by Om3gaOfficial** [mangei/tissquickregistrationscript#25]
The last commit was in 2020 and there are still features listed that would be very cool if they would be implemented

**Comment by Phoenix1747** [comment]
Afaik he cannot test the code anymore (no login or something).

Anyways, I think you answered your own question already 😄

**Comment by mangei** [comment]
Hi @Om3gaOfficial @NuclearPhoenixx , 

it is not maintained anymore. Feel free to fork it and further develop it yourself. 

All the best for your studies! :)
