### ISSUE TITLE
LVA Anmeldung - Nach Refresh wird der Anmeldebutton nicht gedrückt

### ISSUE THREAD

**Issue by mr-tomtom123** [mangei/tissquickregistrationscript#9]
Servus!
Vorerst: Cooles Script :) 
Habe leider ein Problem bei der LVA Anmeldung - er drückt nach dem Refresh der Seite nicht den Anmelde Button!
Wäre sehr fein wenn du auch noch die Prüfungsanmeldung implementieren könntest! ;)
Dankeschön!
LG 
Thomas

**Comment by mangei** [comment]
> Habe leider ein Problem bei der LVA Anmeldung - er drückt nach dem Refresh der Seite nicht den Anmelde Button!

@mr-tomtom123 Könntest du bitte deine Konfigruation und den Link zur LVA Anmeldung posten? Dann kann ich analysieren, warum es nicht ging.

Für die Prüfungsanmeldung, habe ich ein eigenes Ticket erstellt: #10

**Comment by SpiRyu** [comment]
Das Problem hatte ich letztens ebenfalls. Ich konnte es aber durch eine Änderung im Code beheben. Das Problem ist, dass in der Methode "onGroupPage" die ID des groupLabels abgefragt wird (var idAttr = groupLabel.parent().attr('id');). Es kann aber sein, dass dieses gar keine ID hat - war zumindest bei mir der Fall. Ich empfehle, dass einfach ein kurzer Check eingebaut wird, ob die ID überhaupt vorhanden ist, und ansonsten wird sie einfach auf irgendwas gesetzt. Danach kann das Skript wie gehabt fortgeführt werden.

**Comment by steradiant** [comment]
Könntest du bitte kurz erläutern, wie du deine "schnelle Lösung" gemacht hast. Danke!

**Comment by SpiRyu** [comment]
Als QuickFix einfach vor der Zeile "var idAttr = groupLabel.parent().attr('id');" in der Methode onGroupPage einfach folgenden Befehl einfügen:
groubLabel.parent ().attr ('id', 'salamiundschinken');

**Comment by steradiant** [comment]
Danke! Funktioniert bei mir jedoch nach wie vor bei einer normalen LVA ohne Gruppe auch nicht. Der Bestätigungs"klick" wird gemacht, der erste Anmeldeklick jedoch nicht.

**Comment by SpiRyu** [comment]
Gibts irgendeine Ausgabe auf der JavaScript-Konsole?

**Comment by steradiant** [comment]
Ja, folgender Fehler wird ausgegeben:
ERROR: Execution of script 'TISS Quick Registration Script' failed! Cannot read property 'replace' of undefinedi @ VM1061:4(anonymous function) @ VM1061:5c @ VM975:41ja @ VM975:41ma @ VM975:83b @ VM975:83
VM1061:4 TypeError: Cannot read property 'replace' of undefined
    at onGroupPage (eval at <anonymous> (unknown source), <anonymous>:285:24)
    at onLVAPage (eval at <anonymous> (unknown source), <anonymous>:261:9)
    at analysePage (eval at <anonymous> (unknown source), <anonymous>:228:13)
    at tissQuickRegistration (eval at <anonymous> (unknown source), <anonymous>:169:17)
    at TissQuickRegistrationClass (eval at <anonymous> (unknown source), <anonymous>:534:5)

Sorry, kann mangels Erfahrung mit Scripts leider beim Debuggen nicht viel mehr beitragen.

**Comment by SpiRyu** [comment]
Bist du sicher, dass du die aktuelle Version des Scripts hast? In Zeile 285 ist nämlich eigentlich nur ein Kommentar. Ansonsten klingts genauso wie das was mein Befehl oben eigentlich hätte fixen sollen, es wird scheinbar versucht von der ID die Methode replace aufzurufen, aber die ID ist nun mal undefined.

**Comment by mangei** [comment]
Ich hab mir das Problem angesehen und konnte es nachstellen. Es hat sich die Struktur leicht geändert (wie ihr schon festgestellt habt, gibt es keine `id` mehr) und daher hat das Script nicht mehr richtig gearbeitet. Ich hab das und noch weitere Dinge jetzt in v1.5.3 gefixt. Falls euch noch etwas auffällt oder das Problem für euch immer noch besteht, gebt bescheid. Viel Erfolg! :)
